/*
 * File: app/store/Cars.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Cars', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Car'
    ],

    config: {
        data: [
            {
                manufacturer: 'Porsche',
                model: '911',
                price: 135000,
                wiki: 'http://en.wikipedia.org/wiki/Porsche_997',
                img: '2004_Porsche_911_Carrera_type_997.jpg'
            },
            {
                manufacturer: 'Nissan',
                model: 'GT-R',
                price: 80000,
                wiki: 'http://en.wikipedia.org/wiki/Nissan_Gt-r',
                img: '250px-Nissan_GT-R.jpg'
            },
            {
                manufacturer: 'BMW',
                model: 'M3',
                price: 60500,
                wiki: 'http://en.wikipedia.org/wiki/Bmw_m3',
                img: '250px-BMW_M3_E92.jpg'
            },
            {
                manufacturer: 'Audi',
                model: 'S5',
                price: 53000,
                wiki: 'http://en.wikipedia.org/wiki/Audi_S5#Audi_S5',
                img: '250px-Audi_S5.jpg'
            },
            {
                manufacturer: 'Audi',
                model: 'TT',
                price: 40000,
                wiki: 'http://en.wikipedia.org/wiki/Audi_TT',
                img: '250px-2007_Audi_TT_Coupe.jpg'
            }
        ],
        model: 'MyApp.model.Car',
        storeId: 'cars'
    }
});