/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Main', {
    extend: 'Ext.Container',
    alias: 'widget.topct',

    requires: [
        'Ext.ux.CRUDView'
    ],

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'crudview',
                store: 'people'
            },
            {
                xtype: 'segmentedbutton',
                docked: 'bottom',
                allowDepress: true,
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            button.up('topct').child('crudview').setStore('people');
                        },
                        flex: 1,
                        pressed: true,
                        text: 'People'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            button.up('topct').child('crudview').setStore('cars');
                        },
                        flex: 1,
                        text: 'Cars'
                    }
                ]
            }
        ]
    }

});